using Exercicio.PrincipaisPalavras.Service.BlogMinutoSeguro.Interfaces;
using Moq;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace Exercicio.PrincipaisPalavras.Test.Extensions
{
    public static class BlogMinutoSeguroServiceMoqExtensions
    {
        public static Mock<IBlogMinutoSeguroService> ObterConteudoFeed_Topico(this Mock<IBlogMinutoSeguroService> mock)
        {
            mock.Setup(c => c.ObterConteudoFeedAsync())
                .Returns(Task.FromResult(ObterTexto()));

            return mock;
        }

        public static string ObterTexto()
        {
            return @"<item>
		    <title>O valor do seguro dos carros mais vendidos do Brasil em junho</title>
		    <link>https://www.minutoseguros.com.br/blog/seguro-dos-carros-mais-vendidos-brasil-junho-2/</link>
				    <comments>https://www.minutoseguros.com.br/blog/seguro-dos-carros-mais-vendidos-brasil-junho-2/#respond</comments>
				    <pubDate>Fri, 05 Jul 2019 15:36:21 +0000</pubDate>
		    <dc:creator><![CDATA[Minuto Seguros]]></dc:creator>
				    <category><![CDATA[Carro]]></category>
		    <category><![CDATA[Mais Vendidos]]></category>
		    <category><![CDATA[carros mais vendidos]]></category>
		    <category><![CDATA[mais vendidos]]></category>
		    <category><![CDATA[seguro dos carros mais vendidos]]></category>

		    <guid isPermaLink='false'>http://www.minutoseguros.com.br/blog/?p=24470</guid>
				    <description><![CDATA[<p>Única mudança na lista dos carros mais vendidos em comparação ao mês passado é a saída do Corolla e a entrada do Compass; com 34% de aumento nas vendas, Argo, da FIAT, é o veículo que mais ascendeu e Kwid mantém-se na quarta posição</p>
            <p>O post <a rel='nofollow' href='https://www.minutoseguros.com.br/blog/seguro-dos-carros-mais-vendidos-brasil-junho-2/'>O valor do seguro dos carros mais vendidos do Brasil em junho</a> apareceu primeiro em <a rel='nofollow' href='https://www.minutoseguros.com.br/blog'>Blog Minuto Seguros</a>.</p>
            ]]></description>
								            <content:encoded><![CDATA[<p>A Minuto Seguros, uma das principais corretoras do País e líder no segmento de seguros online, acaba de realizar um estudo com base na lista divulgada pela <a href='http://www3.fenabrave.org.br:8082/plus/modulos/listas/index.php'><strong>Fenabrave</strong> </a>(Federação Nacional da Distribuição de Veículos Automotores) com o seguro dos carros mais vendidos no Brasil em junho.</p>
            <p>O <a href='https://www.minutoseguros.com.br/blog/onix-o-carro-mais-vendido-do-ano/'><strong>Onix</strong></a>, da Chevrolet, apesar de manter-se na liderança de mercado teve uma queda de 12% em relação ao mês de maio.  O principal modelo da GM saiu de 22.279 unidades para 19.500, em junho. Já O <a href='https://www.minutoseguros.com.br/blog/conheca-todos-detalhes-valor-seguro-hb20/'><strong>HB20</strong> </a>foi outro modelo que teve queda nas vendas em junho: 19% a menos que o último mês, quando caiu de 10.111 unidades para 8.147. É o segundo mês consecutivo de quedas do hatch da Hyundai que, apesar disso, mantém o posto de segundo carro mais vendido do Brasil no ano.</p>
            <p><img class='wp-image-24475 aligncenter' src='http://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/31879412517_101901a428_b.jpg' alt='' width='815' height='473' srcset='https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/31879412517_101901a428_b.jpg 1024w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/31879412517_101901a428_b-300x174.jpg 300w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/31879412517_101901a428_b-768x446.jpg 768w' sizes='(max-width: 815px) 100vw, 815px' /></p>
            <p>O KA, apesar de ter apresentado queda comparativamente a maio, ultrapassou o HB20 no ranking mensal de mais vendidos com as 8.398 unidades vendidas. Comparativamente ao mês de maio, o KA caiu 14% as suas comercializações. Em junho ele chegou ao número de 8.398, mas em maio ele já havia alcançado 9.484 vendas. Por mais um mês, o quinto consecutivo, as vendas de HB20 e KA não superaram a totalidade de vendas do Onix: 19.500 contra 16.545 dos dois modelos.</p>
            <p align='center'><a class='bt-cotar-blog' href='https://www.minutoseguros.com.br/cotacao-carro/vamos-comecar/?utm_source=blog&amp;utm_medium=botao-cotacao' rel='noopener'><strong>COTE O SEGURO DOS MAIS VENDIDOS</strong></a></p>
            <p>Em junho, o preço médio do seguro do Onix, entre as cinco capitais cotadas, foi de R$1.777 para o público masculino. Em comparação ao mês de maio, houve uma leve subida do preço médio do hatch da Chevrolet: cerca de 2%. A variação é baixa e mostra que, pelo menos entre os meses, houve certa estabilização do preço do seguro.</p>
            <h2><strong>Preço do seguro Onix para mulheres</strong></h2>
            <p>Sobre o perfil feminino para o seguro do Onix, o preço médio nas cinco capitais é de R$1.722. A diferença de valores, em comparação ao mês passado, apresenta outra elevação nos valores, dessa vez, mais perceptível: 8%. Na comparação com os homens, as mulheres pagam menos no valor do seguro do Onix. O valor para elas é, em média, R$55 mais barato do que para eles.</p>
            <p>O Onix, em 2019, no primeiro semestre do ano já vendeu mais de 100 mil carros. Ao total já foram 117.001 até o último dia de junho. Em 2018, nos seis primeiros meses do ano, o hatch da Chevrolet havia vendido 89.261 unidades. O crescimento nas vendas do Onix, ano versus ano, é de 31%. Para efeito de comparação, o Onix só foi ter mais de 100 mil unidades vendidas em 2018 no mês de julho.</p>
            <h2><strong>Apenas uma mudança na lista: sai Corolla entra Compass</strong></h2>
            <p>No mês de junho, a única mudança ficou por conta da saída do Corolla e a entrada do Compass. O SUV da Jeep ficou com a 10ª colocação e 5.080 unidades vendidas. Essa, inclusive, foi a primeira vez que o Jeep Compass entrou na lista dos carros mais vendidos do Brasil em 2019. Em 2018, por exemplo, o modelo era figura mais constante na lista juntamente com o Renegade. Com relação ao preço do seguro do Compass, o SUV ficou com a maior média, tanto para os homens, quanto para as mulheres. Os valores foram R$3.858 e R$3.459, respectivamente.</p>
            <p><img class='size-full wp-image-24474 aligncenter' src='http://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/2015_Toyota_Corolla_Altis_ZRE172R_1.6_sedan_2016-01-03_01.jpg' alt='' width='3769' height='2048' srcset='https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/2015_Toyota_Corolla_Altis_ZRE172R_1.6_sedan_2016-01-03_01.jpg 3769w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/2015_Toyota_Corolla_Altis_ZRE172R_1.6_sedan_2016-01-03_01-300x163.jpg 300w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/2015_Toyota_Corolla_Altis_ZRE172R_1.6_sedan_2016-01-03_01-768x417.jpg 768w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/2015_Toyota_Corolla_Altis_ZRE172R_1.6_sedan_2016-01-03_01-1024x556.jpg 1024w' sizes='(max-width: 3769px) 100vw, 3769px' /></p>
            <p>O <a href='https://www.minutoseguros.com.br/blog/renault-kwid/'><strong>Kwid</strong></a>, da Renault, mostra, por mais um mês, que consolidou-se entre as preferências automotivas brasileiras. Dessa vez, por 265 unidades, ele não passou o HB20 e entrou no TOP3 dos mais vendidos do mês. O mini SUV ficou manteve a quarta posição com a venda de 7.882 unidades. Mesmo com esse bom mês de vendas, comparado a maio, as vendas do Kwid tiveram queda de 9%. Mas, algo que não mudou foi que o mini SUV da Renault manteve o posto de menor média do preço do seguro, tanto para homens, quanto para mulheres.  Para o público masculino o valor médio foi de R$1.741 nas cinco capitais cotadas, já para o público feminino, R$1.542.</p>
            <p><img class='size-full wp-image-24473 aligncenter' src='http://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/kwidcertooutsider.jpg.ximg_.l_full_m.smart_.jpg' alt='kwid na lista dos mais vendidos' width='1500' height='843' srcset='https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/kwidcertooutsider.jpg.ximg_.l_full_m.smart_.jpg 1500w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/kwidcertooutsider.jpg.ximg_.l_full_m.smart_-300x169.jpg 300w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/kwidcertooutsider.jpg.ximg_.l_full_m.smart_-768x432.jpg 768w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/kwidcertooutsider.jpg.ximg_.l_full_m.smart_-1024x575.jpg 1024w' sizes='(max-width: 1500px) 100vw, 1500px' /></p>
            <p>O HB20 está com 2.348 comercializações de vantagem para o Ford KA até o sexto mês do ano. A disputa acirrada pelo posto de segundo carro mais vendido do Brasil parece que vai ser apertada até o final do ano. O KA está consolidado no terceiro lugar e parece que não será incomodado pelo Kwid até o final do ano – a menos que haja alguma surpresa.</p>
            <h2><strong>Preço do seguro da lista dos mais vendidos</strong></h2>
            <p>Os valores do seguro para o HB20 parecem ter estabilizado nos últimos meses, com poucas alterações, tanto para baixo quanto para cima. Se em maio o valor médio para assegurar o carro era R$2.096, em junho, subiu levemente para R$2.159, cerca de 3%. Para as mulheres, o cenário se repete, com poucas alterações: se em maio o preço médio entre as cinco capitais era de R$1.940, em junho subiu para R$2.088, menos de R$150.</p>
            <p>O Ford KA, terceiro carro mais vendido do Brasil e segundo carro mais vendido em junho, comercializou 8.398 carros no sexto mês do ano. O preço médio do seguro do KA para os homens foi de R$2.004. Isso significou um aumento de quase 10% comparado ao último mês, quando o preço estava R$1.826. Já para as mulheres, o valor médio foi de R$1.711, R$106 mais caro o do que no último mês, representando um aumento de 6,6%. É o segundo mês consecutivo que o preço do seguro do KA aumenta nas mesmas proporções para as mulheres no valor médio das cinco capitais.</p>
            <p>O Kwid tomou para si o posto de preço do seguro médio mais barato entre os veículos mais vendidos do Brasil. Nos quatro primeiros meses do ano, o posto foi do KA, que depois passou para o Onix e agora chegou ao Kwid. Para mulheres, o valor foi de R$1.542 e para homens, de R$1.741.</p>
            <h2><strong>Análise do preço do seguro dos carros mais vendidos</strong></h2>
            <p>A somatória dos 10 carros mais vendidos do Brasil teve a primeira queda do ano, após cinco meses de crescentes. Em janeiro foram 70.889, em fevereiro 71.694. Em março, o número bateu 76.039 unidades, em abril foram 83.238 e, agora em maio, 89.095. No entanto, em junho, o número caiu para 80.611, o número mais baixo desde março. Esse dado explica, basicamente, a queda nas vendas dos principais modelos.</p>
            <p>O preço do seguro médio desses 10 veículos ficou no valor de R$2.361 para os homens e de R$2.189 para as mulheres. Para ambos os sexos houve aumento nos valores, 10% para as mulheres e 6,8% para os homens. O aumento no valor médio dos carros mais vendidos aconteceu pela entrada do Compass na lista, que historicamente tem um preço de seguro mais caro por dois fatores: preço de Tabela FIPE alto e manutenção mais cara por conta das peças.</p>
            <p>Para realizar o estudo, a <a href='https://www.minutoseguros.com.br/corretora-de-seguros'><strong>Minuto Seguros</strong></a> considerou como perfil um condutor homem e uma condutora mulher, de 35 anos, ambos casados. Foram avaliados os preços dos seguros em cinco capitais (São Paulo, Rio de Janeiro, Belo Horizonte, Curitiba e Maceió).</p>
            <h2><strong>Quem paga menos pelo seguro do carro?</strong></h2>
            <p>Dentro destes perfis mencionados, o preço do seguro para o Kwid é o que apresenta a menor diferença entre as capitais cotadas para homens. O valor mais alto está no Rio de Janeiro com R$1.911 e o menor em São Paulo, por R$1.397, uma distância de R$514. No contraponto de diferença de valores, ainda citando o público masculino, o HB20 é que tem a maior diferença entre estados: R$1.558. A mais alta no Rio de Janeiro, R$3.185, e a menor em Belo Horizonte, com R$1.627.</p>
            <p>Para os homens, São Paulo foi a cidade com seguro mais barato para oito dos dez veículos. Nos seguros com valores mais altos, o Rio de Janeiro é a cidade que detém os maiores preços: sete dos dez modelos. O preço médio do seguro para homens, em São Paulo, cidade com menor custo, para os 10 carros mais vendidos é de R$1.892. Já no Rio de Janeiro, o preço médio foi de R$2.905.</p>
            <h3><strong>Análise do seguro &#8211; público feminino</strong></h3>
            <p>Agora, falando no perfil feminino, o Kwid também foi o que apresentou a menor diferença entre as capitais cotadas, com uma diferença de R$503, do valor mais alto, que está no Rio de Janeiro, com R$1.767, para o mais baixo, que está em Belo Horizonte, com R$1.264. Falando agora sobre a distância de valores mais alta, o Renegade ficou com a maior: R$1.798. A maior no Rio de Janeiro, com R$4.263 e a menor, também em Belo Horizonte, com R$2.465.</p>
            <p>No âmbito do público feminino, São Paulo e Belo Horizonte foram as cidades com o seguro mais barato: cinco modelos para cada um. Já os valores maiores estão concentrados no Rio de Janeiro com nove dos dez delos concentrados lá. O preço médio do seguro em São Paulo e Belo Horizonte, para as mulheres, ficou com R$1.805 e R$1.916, respectivamente. Já no Rio de Janeiro, o preço médio foi de R$2.844.</p>
            <h2><strong>TABELAS COM OS VALORES DO SEGURO DOS CARROS MAIS VENDIDOS EM JUNHO</strong></h2>
            <p><img class='alignnone wp-image-24471 size-full' src='http://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/Tabela-Mais-Vendidos-Junho-Feminino.jpg' alt='seguro dos carros mais vendidos mulheres' width='1197' height='231' srcset='https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/Tabela-Mais-Vendidos-Junho-Feminino.jpg 1197w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/Tabela-Mais-Vendidos-Junho-Feminino-300x58.jpg 300w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/Tabela-Mais-Vendidos-Junho-Feminino-768x148.jpg 768w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/Tabela-Mais-Vendidos-Junho-Feminino-1024x198.jpg 1024w' sizes='(max-width: 1197px) 100vw, 1197px' /></p>
            <p><img class='alignnone wp-image-24472 size-full' src='http://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/Tabela-Mais-Vendidos-Junho-Masculino.jpg' alt='seguro dos carros mais vendidos homens' width='1189' height='237' srcset='https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/Tabela-Mais-Vendidos-Junho-Masculino.jpg 1189w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/Tabela-Mais-Vendidos-Junho-Masculino-300x60.jpg 300w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/Tabela-Mais-Vendidos-Junho-Masculino-768x153.jpg 768w, https://www.minutoseguros.com.br/blog/wp-content/uploads/2019/07/Tabela-Mais-Vendidos-Junho-Masculino-1024x204.jpg 1024w' sizes='(max-width: 1189px) 100vw, 1189px' /></p>
            <p>O post <a rel='nofollow' href='https://www.minutoseguros.com.br/blog/seguro-dos-carros-mais-vendidos-brasil-junho-2/'>O valor do seguro dos carros mais vendidos do Brasil em junho</a> apareceu primeiro em <a rel='nofollow' href='https://www.minutoseguros.com.br/blog'>Blog Minuto Seguros</a>.</p>
            ]]></content:encoded>
							            <wfw:commentRss>https://www.minutoseguros.com.br/blog/seguro-dos-carros-mais-vendidos-brasil-junho-2/feed/</wfw:commentRss>
		            <slash:comments>0</slash:comments>
							    </item>";
        }
    }
}
